### ISSUE TITLE
Results of statistical analysis

### ISSUE THREAD

**Issue by joshsia** [UBC-MDS/DSCI_522_US_social_determinants_of_health_by_county#25]
I've made a pull request to add the data analysis script. It outputs a figure called `feature_coefs.png` in the `results` directory which shows the coefficients associated with each feature following MLR. Please let me know if this is the plot we want.

Is there anything else we want to analyse? We’re supposed to summarise the results in a table too, but I don’t know what to show.

Do you have any ideas?

**Comment by joshsia** [comment]
It might also be interesting to use sklearn `PolynomialFeatures` (or equivalent) to transform the features and see if we find other relationships in the data. What do you think?

**Comment by morganrosenberg50** [comment]
I think this could be very interesting, given that social determinants are intrinsically complex and often have compounding effects. My only concern is that we may not have the "right" factors included for this kind of analysis, and would be tempted to expand out the number of features (at the expense of my tiny laptop).

Alternatively, I suppose we could start with our current feature set and see what we get

**Comment by morganrosenberg50** [comment]
(once I have confirmation, I can create a small data script which splits the data into train/test)

**Comment by morganrosenberg50** [comment]
As per discussion in lab, given the interesting results of the the linear model and the time restrictions of this lab, let's keep it to focus on linear relationships!
