### ISSUE TITLE
Data wrangling script

### ISSUE THREAD

**Issue by morganrosenberg50** [UBC-MDS/DSCI_522_US_social_determinants_of_health_by_county#26]
Hey team,
I'm almost done the data wrangling script, which will:
- pull together the common/ non-contradictory elements from Alex and Josh's EDA and data analysis work
- splitting out growth rate into average growth rate per county and max growth rate per county
- standardizing the "per capita" columns to "per 100k" for ease of comparison (a few were per 1000, most are per 100k) ---Josh I know you will be standardizing these anyways, but this may be useful for EDA and quick queries

A question: is there utility in nesting our time series data for each county, or is this more trouble and storage space than it's worth?

**Comment by joshsia** [comment]
For this project, I don't think we will be working with time series data, so we won't need to keep it.
