### ISSUE TITLE
Update EDA for milestone2 

### ISSUE THREAD

**Issue by alexYinanGu0** [UBC-MDS/DSCI_522_US_social_determinants_of_health_by_county#32]
Hi team, some updates for EDA.

- I added more descriptive statistics using `str()` to get data types and `unique()` to calculate unique values of each column.
- Instead of lemon package from Milestone1, I used kable this time to yield tables in HTML for better visualization. I will add info about the new packages I used in README "Dependencies".

**Comment by alexYinanGu0** [comment]
In addition, since HTML is not showing in GitHub, we put pdf file last week for milestone1. This week, I put a md file for milestone instead.

**Comment by joshsia** [comment]
The EDA tables and figures look good
