### ISSUE TITLE
Reading data set from Kaggle URL

### ISSUE THREAD

**Issue by joshsia** [UBC-MDS/DSCI_522_US_social_determinants_of_health_by_county#6]
Currently, the `get_data.R` script cannot read the data set from the Kaggle URL directly.

I searched online and it seems like we need to either:
- use an unofficial R API package (https://medium.com/mcd-unison/how-to-use-kaggle-api-to-download-datasets-in-r-312179c7a99c)
- Use the library httr to send a GET request (https://stackoverflow.com/questions/55272909/read-dataset-from-kaggle
- Have the URL be pointing to a zip file, which I’m not sure how to get in Kaggle (https://stackoverflow.com/questions/3053833/using-r-to-download-zipped-data-file-extract-and-import-data)
- Use the library RCurlto act as a web client (https://stackoverflow.com/questions/35303779/downloading-kaggle-zip-files-in-r).

Does anyone have any suggestions on how we should proceed?

**Comment by morganrosenberg50** [comment]
So to simplify things/ as a point of clarity as per a previous convo offline, I think we only need the first/ primary data set, and can disregard the two smaller ones, as all important information was fed into them. Not sure if this is important to which of the above methods to choose, but useful in terms of what we go to the trouble of storing. 

In terms of these methods, the last one (CurlPerform) seems to be pretty plug and play at a glance, which I like, and also more universally useful for similar problems with other websites, however, I'm not familiar with it, so I'm taking it at face value that it would work.

I've also reached out to my alum mentor group to see if they have any advice and will let you know if I hear back!

**Comment by joshsia** [comment]
I've made a new pull request to add the file `get_kaggle_data.R` which is able to read the data set from the Kaggle URL directly, but it requires the user to specify the filename. It also requires a `kaggle.json` file at the project root.

**Comment by joshsia** [comment]
Requirements are specified in the README
