### ISSUE TITLE
Update of EDA

### ISSUE THREAD

**Issue by alexYinanGu0** [UBC-MDS/DSCI_522_US_social_determinants_of_health_by_county#8]
- EDA part 1 we decided on a table for all counties. However, I also put a table for each state there just in case because we have 1900+ counties and a shorter table could be easier to interpret.
- The feature "death" is binary, so I deleted it because we cannot group it by county or state.
- A set of density plots is added as well to demonstrate the distribution of numeric variables. 

Please give it a check and don't hesitate to add new ideas or changes to make it neater and cleaner!
[EDA.pdf](https://github.com/UBC-MDS/DSCI_522_US_social_determinants_of_health_by_county/files/7576882/EDA.pdf)

**Comment by morganrosenberg50** [comment]
This looks great. I think it was intelligent to include covid growth rate against total cases to model an intuitive linear relationship for comparison with the other variables. I wonder if it may be worthwhile to put the tables into a dataframe format for readability? 

It may also be cool to add some interactivity (like tooltip in py) to click in and see the county names of outliers: https://plotly.com/ggplot2/interactive-tooltip/

**Comment by alexYinanGu0** [comment]
Good call! I added the interactivity to EDA. 
To display the interactivity, we need to render the file to HTML. However, the dataframes do not look pretty in HTML, so I also used an R package called "lemon" for better display. Please check the updated version and let me know your thoughts! 

p.s. I cannot add HTML file here so please go to the EDA file and see the updates, thanks!

**Comment by joshsia** [comment]
I think the EDA looks ok, but some comments:
- Could you change “group 25” to our names?
- Some of the code seem to go beyond the grey area in the pdf file. Could you put these in a new line?
Visualisations 1 and 2's titles are cropped. Also, can you change the x-axis scale to SI units? So it looks like 10k, 20k, etc.
- I think it’s better to have the density plots before Visualisations 1 and 2. Also the x-axis scales might be better if they were in SI units.
Some of the variable names seem to not fit in the facet subplot. Do you know if this can be easily fixed?

**Comment by alexYinanGu0** [comment]
Thanks for the suggestions! Changed accordingly.
